[tox]
envlist = py311
requires = tox>=4

[testenv]
description = Run tests with pytest
package = editable         # install your src/ package in editable mode
extras = dev               # assumes pytest etc. live under [project.optional-dependencies].dev
commands =
    pytest -q {posargs:tests}
